spring:
    redis:
        host: 127.0.0.1
        port: 6379
logging:
    level:
        root: info
        com.likego.blog: debug
    file: log/blog-dev.log
server:
    port: 8083
kdxfConfig:
    appid: "5e4cb2a5"
    secretid: "fb3e810f1cbfb391594241d6ddfd1c6e"
ffmpeg:
    filepath: "/Users/shaominchen/Documents/software/Util/ffmpeg-20200227-9b22254-macos64-static/bin/ffmpeg"
queue:
    max_size: 10
file_piece_size: 10485760
kdxf_host:
    url: "http://raasr.xfyun.cn/api"

